name: Tear Down Azure Container App

on:
  workflow_dispatch:  # Allows manual trigger of the workflow from GitHub UI

jobs:
  teardown:
    runs-on: ubuntu-latest
    
    steps:
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Azure Container App
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Running Azure CLI commands to delete resources..."
            # Delete the Azure Container App
            az containerapp delete --name virtual-pet-backend --resource-group virtual-pet-backend --yes --no-wait

      - name: Delete Azure Container App Environment
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Running Azure CLI commands to delete resources..."
            # Delete the Azure Container App Environment
            az containerapp env delete --name virtual-pet-backend-env --resource-group virtual-pet-backend --yes --no-wait

      - name: Confirm Deletion
        run: |
          echo "The container app and associated resources have been deleted. Check the Azure Portal for confirmation."
